version: '3'
services:
  tor:
    image: try2codesecure/docker_tord
    ports:
      - 9001:9001
      - 9030:9030
    volumes:
      - ./tor-conf:/etc/tor:ro
      - tor-data:/var/lib/tor

volumes:
  tor-data: